version: '3.7'

services:
  service:
    image: "menoncello/scheduler"
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      RABBIT_URL: ${RABBIT_URL}
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1

networks:
  backend:
    external: true
