name: Publish Docker image

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: ./Dockerfile
          no-cache: true
          push: true
          tags: menoncello/scheduler

      - name: deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: master01.vps.webdock.io
          user: deployer
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          first_ssh: |
            mkdir -p /home/deployer/scheduler
          scp: |
            './*' => /home/deployer/scheduler/
          last_ssh: |
            export MONGO_DB=${{ secrets.MONGO_DB }}
            export MONGO_HOST=${{ secrets.MONGO_HOST }}
            export RABBIT_URL=${{ secrets.RABBIT_URL }}
            docker stack deploy --compose-file /home/deployer/scheduler/docker-compose.yml podcast-updater
            rm -rf /home/deployer/scheduler
